name: Push branch & Deploy

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 배포한 사용자
        required: true
        type: string
      stage_choice:
        description: 배포 유형 (production,devleop)
        type: choice
        options:
          - develop
          - production
  workflow_call:
    inputs:
      user_name:
        description: 배포한 사용자
        required: true
        type: string
      stage:
        description: 배포 유형(production,develop)
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

env:
  DEVELOP_REPOSITORY: deploy-sambad-develop
  PRODUCTION_REPOSITORY: deploy-sambad

jobs:
  variable:
    name: set the target STAGE
    runs-on: ubuntu-latest
    outputs:
      destination-repository: ${{inputs.stage == 'production' && env.PRODUCTION_REPOSITORY && env.DEVELOP_REPOSITORY}}
    steps:
      - name: get variables
        run: echo $destination-repository

  build:
    needs: variable
    runs-on: ubuntu-latest
    container: pandoc/latex
    outputs:
      destination-repository: ${{needs.variable.outputs.destination-repository}}
      target-branch: ${{steps.deploy-information.outputs.target-branch}}
    steps:
      - uses: actions/checkout@v4
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates ouput
        run: sh ./tools/build.sh
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'sambad-adventure'
          destination-repository-name: ${{needs.variable.outputs.destination-repository}}
          user-email: ${{secrets.EMAIL}}
          commit-message: ${{github.event.commits.message}}
          target-branch: ${{inputs.stage == 'prodction' && 'main' || 'main' }}
      - name: get deploy information
        id: deploy-information
        run: echo "target-repository=${{needs.variable.outputs.destination-repository}}" >> "$GITHUB_OUTPUT" |
          echo "target-branch=${{inputs.stage == 'prodction' && 'main' || 'main' }}" >> "$GITHUB_OUTPUT"
  info:
    name: get deploy information
    runs-on: ubuntu-latest
    needs: build
    steps:
      - env:
          destination-repository: ${{needs.build.outputs.destination-repository}}
          target-branch: ${{needs.build.outputs.target-branch}}
        run: |
          echo "$destination-repository" |
          echo "$target-branch"
