name: Slack Notification

on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created, edited]

jobs:
  send_slack_notification:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification for PR creation
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: author,pullRequest
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Actor: ${process.env.AS_AUTHOR}
                PR: ${process.env.AS_PULL_REQUEST}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Extract mentions from comment body
        id: extract_mentions_comment
        if: github.event_name == 'issue_comment'
        run: |
          mentions=$(echo "${{ github.event.comment.body }}" | grep -o '@[[:alnum:]_-]\+' | paste -sd ' ' -)
          echo "::set-output name=mentions::$mentions"

      - name: Map GitHub mentions to Slack user IDs
        id: map_to_slack_ids
        if: github.event_name == 'issue_comment'
        run: |
          declare -A slack_ids
          slack_ids=(["@Doeunnkimm"]="U07600UQG3T" ["@semnil5202"]="U075KR29RGR" ["@Andrevile"]="U07545VMS21" ["@LeeJeongHooo"]="U075C1A16LT")
          mentions="${{ steps.extract_mentions_comment.outputs.mentions }}"
          slack_mentions=""
          for mention in $mentions; do
            if [[ -n "${slack_ids[$mention]}" ]]; then
              slack_mentions="$slack_mentions <@${slack_ids[$mention]}>"
            fi
          done
          echo "::set-output name=slack_mentions::$slack_mentions"

      - name: Send Slack Notification for comment if team members mentioned
        if: ${{ github.event_name == 'issue_comment' && steps.map_to_slack_ids.outputs.slack_mentions != '' }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: pullRequest
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_PULL_REQUEST} 에서 ${{ steps.map_to_slack_ids.outputs.slack_mentions }} 님을 언급했습니다.
                꼭 나중에 들어가서 확인하기!
                메시지: ${{ github.event.comment.body }}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Debug mentions
        if: ${{ github.event_name == 'issue_comment' && steps.map_to_slack_ids.outputs.slack_mentions == '' }}
        run: echo "No team members mentioned in the comment."
